safe: false
pygments: true
permalink: /:title
markdown: rdiscount
plugins: docs/_plugins/

title: Rust Design Patterns - Josh Davis
name: Rust Design Patterns
description: Design Patterns in Rust Language
base: http://joshldavis.com/
url: http://joshldavis.com/rust-design-patterns
feed: /atom.xml

author: Josh Davis
contact: hello@joshldavis.com

css:
    - /css/base.css
    - /lib/font-awesome/css/font-awesome.min.css
    - http://fonts.googleapis.com/css?family=Droid+Sans
